version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
    open-pull-requests-limit: 10
    assignees:
      - "bparanj"
    reviewers:
      - "bparanj"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
      - "automated"
    groups:
      grpc-ecosystem:
        patterns:
          - "google.golang.org/grpc*"
          - "google.golang.org/protobuf*"
          - "google.golang.org/genproto*"
      spiffe-ecosystem:
        patterns:
          - "github.com/spiffe/go-spiffe*"
      opentelemetry-ecosystem:
        patterns:
          - "go.opentelemetry.io/*"
      security-critical:
        patterns:
          - "golang.org/x/crypto*"
          - "golang.org/x/net*"
          - "golang.org/x/sys*"
        update-types:
          - "patch"
          - "minor"
      test-dependencies:
        patterns:
          - "github.com/stretchr/testify*"
          - "*test*"
    # Enhanced security focus for 2025
    ignore:
      # Ignore major version updates for stability
      - dependency-name: "google.golang.org/grpc"
        update-types: ["version-update:semver-major"]
      - dependency-name: "github.com/spiffe/go-spiffe/v2"
        update-types: ["version-update:semver-major"]
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "02:00"
    open-pull-requests-limit: 3
    assignees:
      - "bparanj"
    reviewers:
      - "bparanj"
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"