name: 'Setup Go Environment'
description: 'Setup Go with caching and version verification'
inputs:
  go-version:
    description: 'Go version to install'
    required: false
    default: '1.23'
  verify-version:
    description: 'Whether to verify the Go version matches expected'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
    
    - name: Clear Go caches (prevent stale cache issues)
      shell: bash
      run: |
        echo "🧹 Clearing Go caches to prevent stale build issues..."
        go clean -cache || true
        go clean -testcache || true
        go clean -modcache || true
        echo "✅ Go caches cleared"
        
    - name: Verify Go version
      if: ${{ inputs.verify-version == 'true' }}
      shell: bash
      run: |
        echo "Expected Go version: ${GO_VERSION}"
        echo "Actual Go version: $(go version)"
        go version | grep -E "(go1\.(22|23))" || (echo "ERROR: Go version is not 1.22 or 1.23" && exit 1)
      env:
        GO_VERSION: ${{ inputs.go-version }}
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ inputs.go-version }}-${{ hashFiles('**/go.sum') }}-${{ github.run_number }}
        restore-keys: |
          ${{ runner.os }}-go-${{ inputs.go-version }}-${{ hashFiles('**/go.sum') }}-
          ${{ runner.os }}-go-${{ inputs.go-version }}-
          ${{ runner.os }}-go-
          
    - name: Download dependencies
      shell: bash
      run: go mod download