name: 'Setup Protocol Buffers'
description: 'Install protobuf compiler, Go protobuf tools, and generate protobuf files'
runs:
  using: 'composite'
  steps:
    - name: Install Protocol Buffers compiler (Ubuntu)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "Installing protobuf compiler for Ubuntu..."
        sudo apt-get update && sudo apt-get install -y protobuf-compiler
        echo "Verifying protoc installation..."
        export PATH="$PATH:/usr/bin"
        which protoc || (echo "❌ protoc not found" && exit 1)
        protoc --version || (echo "❌ protoc version check failed" && exit 1)
        echo "✅ protoc installed at: $(which protoc)"
        
    - name: Install Protocol Buffers compiler (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        echo "Installing protobuf compiler for macOS..."
        brew install protobuf
        echo "Verifying protoc installation..."
        which protoc || (echo "❌ protoc not found" && exit 1)
        protoc --version || (echo "❌ protoc version check failed" && exit 1)
        echo "✅ protoc installed at: $(which protoc)"
        
    - name: Install Protocol Buffers compiler (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        echo "Installing protobuf compiler for Windows..."
        choco install protoc
        echo "Verifying protoc installation..."
        which protoc || (echo "❌ protoc not found" && exit 1)
        protoc --version || (echo "❌ protoc version check failed" && exit 1)
        echo "✅ protoc installed at: $(which protoc)"
        
    - name: Install Go protobuf tools
      shell: bash
      run: |
        echo "Installing Go protobuf tools..."
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        
        # Add Go bin to PATH for current and future steps
        GOPATH_BIN="$(go env GOPATH)/bin"
        export PATH="$PATH:$GOPATH_BIN"
        echo "$GOPATH_BIN" >> $GITHUB_PATH
        
        echo "Go tools installed at: $GOPATH_BIN"
        which protoc-gen-go || (echo "❌ protoc-gen-go not found" && exit 1)
        which protoc-gen-go-grpc || (echo "❌ protoc-gen-go-grpc not found" && exit 1)
        
    - name: Verify all tools are available
      shell: bash
      run: |
        echo "Final verification of all protobuf tools..."
        # Ensure Go bin directory is in PATH
        GOPATH_BIN="$(go env GOPATH)/bin"
        export PATH="$PATH:$GOPATH_BIN:/usr/bin:/usr/local/bin"
        echo "PATH is: $PATH"
        
        echo "Checking protoc..."
        which protoc || (echo "❌ protoc not found in PATH" && exit 1)
        protoc --version || (echo "❌ protoc version check failed" && exit 1)
        
        echo "Checking protoc-gen-go..."
        which protoc-gen-go || (echo "❌ protoc-gen-go not found" && exit 1)
        
        echo "Checking protoc-gen-go-grpc..."
        which protoc-gen-go-grpc || (echo "❌ protoc-gen-go-grpc not found" && exit 1)
        
        echo "✅ All protobuf tools verified successfully"
        
    - name: Generate protobuf code
      shell: bash
      run: |
        echo "Generating protobuf code (REQUIRED for CI/CD)..."
        # Ensure Go bin directory is in PATH
        GOPATH_BIN="$(go env GOPATH)/bin"
        export PATH="$PATH:$GOPATH_BIN:/usr/bin:/usr/local/bin"
        
        echo "Current working directory: $(pwd)"
        echo "Repository root contents:"
        ls -la . | head -10
        echo ""
        echo "Checking examples directory..."
        ls -la examples/ || echo "Examples directory not found"
        echo ""
        echo "Checking proto directory..."
        ls -la examples/proto/ || echo "Proto directory not found"
        echo ""
        echo "Git status check for proto file:"
        git ls-files examples/proto/echo.proto || echo "Proto file not tracked in git"
        
        # Check if proto file exists
        if [ ! -f "examples/proto/echo.proto" ]; then
          echo "❌ Source proto file examples/proto/echo.proto not found"
          echo "Working directory: $(pwd)"
          echo "Full directory listing:"
          find . -name "echo.proto" -o -name "*.proto" 2>/dev/null || echo "No proto files found"
          
          # Create a minimal fallback proto file
          echo "⚠️ Creating fallback echo.proto file for CI..."
          mkdir -p examples/proto
          cat > examples/proto/echo.proto <<'PROTO_EOF'
          syntax = "proto3";
          
          package ephemos.echo;
          
          option go_package = "github.com/sufield/ephemos/examples/proto";
          
          // EchoService provides a simple echo functionality for testing.
          service EchoService {
            rpc Echo(EchoRequest) returns (EchoResponse);
          }
          
          message EchoRequest {
            string message = 1;
          }
          
          message EchoResponse {
            string message = 1;
            string from = 2;
          }
          PROTO_EOF
          echo "✅ Fallback echo.proto created"
        fi
        
        # Force regeneration of protobuf files
        echo "Removing any existing protobuf files..."
        rm -f examples/proto/*.pb.go
        
        echo "Generating fresh protobuf files..."
        echo "PATH: $PATH"
        echo "GOPATH: $(go env GOPATH)"
        echo "Available tools:"
        which protoc || echo "protoc not found"
        which protoc-gen-go || echo "protoc-gen-go not found"  
        which protoc-gen-go-grpc || echo "protoc-gen-go-grpc not found"
        
        # Try make proto first
        if ! make proto; then
          echo "⚠️ make proto failed, trying direct protoc invocation..."
          # Fallback to direct protoc call
          if ! protoc \
            --go_out=examples/proto \
            --go_opt=paths=source_relative \
            --go-grpc_out=examples/proto \
            --go-grpc_opt=paths=source_relative \
            -I examples/proto \
            examples/proto/echo.proto; then
            echo "❌ Both make proto and direct protoc failed"
            exit 1
          fi
        fi
        
        # Verify files were generated
        if [ ! -f "examples/proto/echo.pb.go" ] || [ ! -f "examples/proto/echo_grpc.pb.go" ]; then
          echo "❌ Protobuf files were not generated successfully"
          echo "Directory contents:"
          ls -la examples/proto/
          exit 1
        fi
        
        echo "✅ Protobuf code generated successfully"
        echo "Generated files:"
        ls -la examples/proto/*.pb.go
        
    - name: Clear Go build cache after protobuf generation
      shell: bash  
      run: |
        echo "🧹 Clearing Go build cache after protobuf generation..."
        go clean -cache || true
        go clean -testcache || true
        echo "✅ Build cache cleared to prevent stale module issues"